services:
  backend:
    build:
      context: ./backend
    container_name: backend-classements
    restart: always
    networks:
      - classements_network
    environment:
      - CLUB_IDS=8422,200608
      - HTTP_PORT=5050
      - NODE_ENV=production
    ports:
      - "5050:5050"

  frontend:
    build:
      context: ./frontend
    container_name: frontend-classements
    restart: always
    networks:
      - classements_network
    environment:
      - REACT_APP_API_BASE_URL=https://api.classements.esmorannes.com
    ports:
      - "8082:8082"

networks:
  classements_network:
    external: true
